# Generated by Django 4.0.1 on 2022-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_barcode', models.IntegerField()),
                ('Promotions_title', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=30)),
                ('Mcode', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('available_for', models.CharField(max_length=30)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
