# Generated by Django 4.0.1 on 2022-02-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfgadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPromotion',
            fields=[
                ('station_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50, null=True)),
                ('operation_region', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('promo_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='promotions',
            name='quantity',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotions',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='start_date',
            field=models.DateField(),
        ),
    ]
