# Generated by Django 4.0.1 on 2022-01-31 13:08

from django.db import migrations, models
import sqlalchemy.expression


class Migration(migrations.Migration):

    dependencies = [
        ('mfgadmin', '0002_alter_promotions_end_date_alter_promotions_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPromotion',
            fields=[
                ('station_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('operation_region', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='promotions',
            name='quantity',
            field=models.IntegerField(default=sqlalchemy.expression.null),
        ),
    ]
