# Generated by Django 4.0.1 on 2022-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfgadmin', '0002_assignpromotion_promotions_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='retail_barcode',
            field=models.IntegerField(null=True),
        ),
    ]
